# Generated by Django 4.0.1 on 2022-01-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_post_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.ImageField(default='default.PNG', upload_to='post_pics'),
        ),
    ]
